### ISSUE TITLE
Improve layout of country-specific page

### ISSUE THREAD

**Issue by hbandukw** [UBC-MDS/DSCI-532_2024_1_TBtracker#106]
- [ ] Separate the risk factors plots from the line plots in some way. Options discussed:
- move the country selection up or make bar and pie charts smaller to incorporate a vertical gray line.
- Add a note about the data being from 2022

- [ ] Make font colours consistent.

**Comment by sean-m-mckay** [comment]
- Can separate graphs over time and most recent, and use different background colours  for each section
