### ISSUE TITLE
Feedback from Joel M4

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_1_TBtracker#111]
Implement eight minor

Minor:
- [x] Log scale colormap
- [x] Unique years in dropdown
- [x] #130
- [x] Try different positions of the card
- [x] Round relative numbers in tooltip
- [x] Remove tooltip titles
- [x] Dropdown f m to "female" "male'
- [x] Sort bars
- [x] Pie percentages don't add up to one disclaimer
- [x] Indicate that bottom panel is not responding to year dropdown
    - [x] Shading? Most recent?

**Comment by zywkloo** [comment]
We address all Joel's feedback in Milestone 4
