### ISSUE TITLE
Reflections

### ISSUE THREAD

**Issue by hbandukw** [UBC-MDS/DSCI-532_2024_1_TBtracker#126]
Hi everyone, I am adding what I did this week for m4_reflections. Please add all the modifications and feedback you addressed.

### Performance Optimization
-  Use a binary format for loading data faster: we switched to `parquet`
- Have no redundant filtering/mutating of the data in the app
- Create a processed data file that is loaded in the app instead (stored in data/processed).
- Have no excessively slow computation that could be easily sped up, e.g. no row-wise use of apply unless well justified and optimized.
- Use caching for at least one function: lru_cache

#### Relative Metric:
- Previously, relative global incidence and mortality stats were calculated by summing rate estimates. This method has been corrected to:
(Total Incidence or Mortality / Total Population) * 100
- Changes in relative incidence/mortality rates are now rounded to 5 decimal points, accommodating the small magnitude of changes, compared to the previous 1 decimal point.

### Logo/Title Redesign
- A new logo has been designed, enhancing the visual identity of the application and added as a flavicon
- Updated title from Dash to "Tb tracker"

### Country-Specific Tab Enhancements
- Barchart gender labels have been updated from 'm/f' to "male" and "female" to improve readability. (Point 4 from https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82)
- The “Select” tabs for the barchart now feature descriptive labels, such as “Select Age Group(s)” and “Select Sex”, clarifying the selection process. (Point 4 from https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82)
- Added a disclaimer under pie chart ([Addresses Ian's feedback on risk factor data](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/111))
- Increased font size for legend and moved it above the chart (https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/97)
- Use log scale for absolute numbers in the colour map ([Addressed Jo's feedback](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/76))
- Changed colour scheme on all graphs on country page, and added title in purple over top of line plots (addressed feedback from Milestone 2 -  The title style lacks uniformity across the plots within the country tab)
- Added disclaimer for 2022 data being the only year risk factor data is available, and visually separated graphs by filling in the rows ([Addresses feedback from Joel](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/111))

#### Card
- Displaying relative numbers as percentages in cards (Point 3 from https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82)
- Adjusted card position to avoid obscuring countries ([Addresses Ian's feedback Point 2](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82))

#### Global Map 
- Addressed [Ian’s feedback](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82#issue-2241716597) by rounding values in the tooltip to 5 decimals and displaying them as percentages
- Addressed [Kittipong’s Feedback](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/76) by adapting the color scale of the geochart to purple/yellow
- Added description for relative metric, which was requested [here](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/76)
- Addressed [Rachel’s feedback](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/67#issue-2232249146) by renaming the legend title
- As suggested [here](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/67#issue-2232249146), we added a comment that uses can hover and click on countries
- Since we found that filling the missing country statistics with -1 values was causing the Global Statistics and the colour scales to be skewed, we instead kept the NA values, and solved the issue of missing countries in the world map by using a base map layer from a shapefile coloured in grey
- Total incidence is now calculated as just "e_inc_num", rather than "e_inc_num" + "e_inc_tbhiv_num", since the tbhiv_num is already included in the overall estimate

### Readme Improvements
- Usage instructions have been refined to ensure clarity and better guide users. (Point 1 from https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82) 

## Miscellaneous App Refinement
- Countries with no data for a given year are coloured grey
- Make the years in the dropdown unique
- Removed default Altair/plotly icons

## Addressing Challenging exercise
- partially addressed challenging exercise by adding docstrings to the functions

## Notes
As a peer review it was mentioned that the hover tooltip from the global map persists after clicking and being redirected to the new tab. We talked with Joel about this issue: It seems to be a bug in Altair and nothing that can be fixed by us!

Also it was mentioned that the year dropdown should be changed to a time range slider. However, after talking to Joel, we decided that a dragdown is a better choice!

Since the bar chart was completely removed from our first tab, there was no need to address the feedback related to that.

[Rachel](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/67#issue-2232249146) mentioned one bug in the bar chart on the country-specific tab, that could not be replicated by us!

Regarding the scrolling issue: We could identify that the deisgn/layout highly differs depending on which resolution the laptop has. On three of our screens it looks good; however it is hard to generalize!

**Comment by zywkloo** [comment]
We addressed all of Vincent, Joel, and Ian 's feedback

# Modifications for App refinement

1. Use a binary format for loading data faster: we switched to `parquet`
2. Have no redundant filtering/mutating of the data in the app
3. Create a processed data file that is loaded in the app instead (stored in data/processed).
Have no excessively slow computation that could be easily sped up, e.g. no row-wise use of apply unless well justified and optimized.
4. Use caching for at least one function: lru_cache

# Feedback Addressed
1. Optimized the card: re-positioning and reformatting

**Comment by sean-m-mckay** [comment]
## Modifications for App refinement
- Since we found that filling the missing country statistics with -1 values was causing the Global Statistics and the colour scales to be skewed, we instead kept the NA values, and solved the issue of missing countries in the world map by using a base map layer from a shapefile coloured in grey
- Total incidence is now calculated as just "e_inc_num", rather than "e_inc_num" + "e_inc_tbhiv_num", since the tbhiv_num is already included in the overall estimate

## Feedback Addressed
- Use log scale for absolute numbers in the colour map ([Addressed Jo's feedback](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/76))
- Changed colour scheme on all graphs on country page, and added title in purple over top of line plots (addressed feedback from Milestone 2 -  The title style lacks uniformity across the plots within the country tab)
- Added disclaimer for 2022 data being the only year risk factor data is available, and visually separated graphs by filling in the rows ([Addresses feedback from Joel](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/111))
 - Increased font size for legend and moved it above the chart (https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/97)
 - Added a disclaimer under pie chart ([Addresses Ian's feedback on risk factor data](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/111))
 - Adjusted card position to avoid obscuring countries ([Addresses Ian's feedback Point 2](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82))

**Comment by sandygross** [comment]
I added my reflections to Hinas comment!

**Comment by sandygross** [comment]
I added the comment about my doing the dcostrings in Hinas comment as well

**Comment by hbandukw** [comment]
Hi everyone, I am adding what I did this week for m4_reflections. Please add all the modifications and feedback you addressed.

## Modifications for further App Refinement
### Metric Calculation Adjustment
#### Relative Metric:
- Previously, relative global incidence and mortality stats were calculated by summing rate estimates. This method has been corrected to:
(Total Incidence or Mortality / Total Population) * 100
- Changes in relative incidence/mortality rates are now rounded to 5 decimal points, accommodating the small magnitude of changes, compared to the previous 1 decimal point.

### Logo/Title Redesign
- A new logo has been designed, enhancing the visual identity of the application and added as a flavicon
- Updated title from Dash to "Tb tracker"

## Feedback Incorporation

### Global tab
- Displaying relative numbers as percentages in cards (Point 3 from https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82)

### Country-Specific Tab Enhancements
- Barchart gender labels have been updated from 'm/f' to "male" and "female" to improve readability. (Point 4 from https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82)
- The “Select” tabs for the barchart now feature descriptive labels, such as “Select Age Group(s)” and “Select Sex”, clarifying the selection process. (Point 4 from https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82)

### Global Map Enhancements
- Addressed [Ian’s feedback](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82#issue-2241716597) by rounding values in the tooltip to 5 decimals and displaying them as percentages
- Addressed [Kittipong’s Feedback](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/76) by adapting the color scale of the geschart to purple/yellow
- Added description for relative metric, which was requested [here](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/76)
- Addressed [Rachel’s feedback](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/67#issue-2232249146) by renaming the legend title
- As suggested [here](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/67#issue-2232249146), we added a comment that uses can hover and click on countries

### Readme Improvements
- Usage instructions have been refined to ensure clarity and better guide users. (Point 1 from https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/82) 

## Further App Refinement
- Color unavailable countries in grey
- Make the years in the dropdown unique
- Removed default Altair/plotly icons

## Addressing Challenging exercise
- partially addressed challenging exercise by adding docstrings to the functions

## Notes
As a peer review it was mentioned that the hover tooltip from the global map persists after clicking and being redirected to the new tab. We talked with Joel about this issue: It seems to be a bug in Altait and nothing that can be fixed by us!

Also it was mentioned that the year dropdown should be changed to a time range slider. However, after talking to Joel, we decided that a dragdown is a better choice!

Since the bar chart was completely removed from our first tab, there was no need to address the feedback related to that.

[Rachel](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/67#issue-2232249146) mentioned one bug in the bar chart on the country-specific tab, that could not be replicated by us!

Regarding the scrolling issue: We could identify that the deisgn/layout highly differs depending on which resolution the laptop has. On three of our screens it looks good; however it is hard to generalize!
