### ISSUE TITLE
Country Tab: Risk Factors Bar Chart

### ISSUE THREAD

**Issue by sean-m-mckay** [UBC-MDS/DSCI-532_2024_1_TBtracker#23]
Interactive chart with toggles for Age and Gender

**Comment by hbandukw** [comment]
Hey I think this is a duplicate? 

https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/issues/34

**Comment by sean-m-mckay** [comment]
@hbandukw I opened one for the graph and one for the toggles : ) cus the graph itself is a good chunk of work. But I can close this as completed since it's easier to have them done together
