### ISSUE TITLE
Create Animation of App

### ISSUE THREAD

**Issue by sean-m-mckay** [UBC-MDS/DSCI-532_2024_1_TBtracker#32]
- Create an animation of your app in action and save it as `img/demo.gif`.
  - You can record your screen while demoing how the app updates when you make selections in the input widgets.
    If you don't have a local program for converting video to GIF,
    I have found [ezgif](https://ezgif.com/video-to-gif) quite helpful in the past.

**Comment by zywkloo** [comment]
Done
