### ISSUE TITLE
Country Tab: Add toggles to risk factor chart

### ISSUE THREAD

**Issue by sean-m-mckay** [UBC-MDS/DSCI-532_2024_1_TBtracker#34]

**Comment by hbandukw** [comment]
Hi everyone, 

I have added the first version of the barchart with sex and age. Here is a demo:

https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/assets/20444993/a47aab97-2d52-43e0-944a-41d0619b305e

Things to do:
- convert the dropdowns to buttons
- Currently, the code is setup to subset the dataframe based on selected country. We need to merge that with our overall functionality for seeing stats for a specific country.
- Restructure the code
