### ISSUE TITLE
Data cleaning and preprocessing

### ISSUE THREAD

**Issue by sean-m-mckay** [UBC-MDS/DSCI-532_2024_1_TBtracker#35]
This task will be influenced by the data requirements for each of the graphs - standardize between graphs

**Comment by hbandukw** [comment]
Hi everyone, I didn't need to do any permanent processing for the barchart. If anyone produced processed data (i.e. saved it as a csv file) can you let me know and point me to the code?

**Comment by sean-m-mckay** [comment]
@hbandukw moved some of the code you had in the other file to preprocessing as part of [this pr](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/pull/39/files#diff-544394d7de47b23c08cde71180646f1064b04f747029b249d2c7b8546cd43a78) hope that's ok
