### ISSUE TITLE
Proposal: App Sketch and Description

### ISSUE THREAD

**Issue by sean-m-mckay** [UBC-MDS/DSCI-532_2024_1_TBtracker#5]
Work on a sketch as a group, then finalize afterwards

Description
------------------------------
Create a sketch of what you envision your app to look like.
Your sketch can be hand-drawn
or put together using a graphics editor or
slide show software.
The sketch should be saved as `img/sketch.png` and linked in this section of the proposal
so that the image shows up when reading the proposal on GitHub.

Example sketch 
(this sketch was drawn using Powerpoint
with icons from the [noun project](https://thenounproject.com/):

![Dashboard](sketch.png "App Sketch")

Complement the sketch with
a high level description of the main components in the app interface
and how the user will interact with it.
You are not required to use terminology specific to Dash/Shiny
(i.e. widgets, components, etc...).

Remember to be realistic about your expectations and plans
since you will actually be implementing this app
(but again, you will not be penalized if you need to adjust a bit in later milestones).
It is better to design a slightly more limited app
that you have time to implement well,
instead of a complicated app that you don't have time to finish.
At the same time,
you cannot just make a single bar chart and call it a day;
the app needs to have several input and output panels.
You can view the dashboards from previous years students
in the [DSCI 532 showcase](https://five32-dashboard-showcase.onrender.com)
(might take several seconds to load)
as a complexity target and to get inspiration for your final app.
Your TA will be able to help you with this as well,
and provide feedback on whether your app is too simple or too complex.

Example description:

> The app contains a landing page that shows the distribution
> (depending on data type, bar chart, density chart etc)
> of dataset factors (hypertension, physical disabilities etc.)
> colored coded according to whether patients showed up or didn't show up for an appointment.
> From a dropdown list,
> users can filter out variables from the distribution display,
> by patient demographics (i.e. only show female patients),
> by appointment data (i.e. if SMS was sent),
> and finally by the date range of appointments.
> A different dropdown menu will allow users to re-order variables
> according to the probability of patients being a no-show
> or in alphabetical order to comorbidities.
> Users can compare the distribution of co-morbidities
> by scrolling down through the app interface.

**Comment by hbandukw** [comment]
<img width="855" alt="main_page_mockup" src="https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/assets/20444993/a30119dc-77c6-40c0-a0ae-7be38fc4e6f7">

Hi everyone, this is the rough mock-up for our main page showing the global trends of TB.

**Comment by hbandukw** [comment]
<img width="795" alt="Screen Shot 2024-03-27 at 8 18 22 AM" src="https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/assets/20444993/3ea5dd42-96ec-40c6-9c6f-1e29bf044e71">

This is a rough mock-up for our second page AFTER clicking on a specific country on the map e.g. in this case, if we clicked on Canada, we would see this.

This one needs a bit of work, I am open to suggestions!

**Comment by zywkloo** [comment]
> <img alt="Screen Shot 2024-03-27 at 8 18 22 AM" width="795" src="https://private-user-images.githubusercontent.com/20444993/317328510-3ea5dd42-96ec-40c6-9c6f-1e29bf044e71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTcxOTcsIm5iZiI6MTcxMTU1Njg5NywicGF0aCI6Ii8yMDQ0NDk5My8zMTczMjg1MTAtM2VhNWRkNDItOTZlYy00MGM2LTljNmYtMWUyOWJmMDQ0ZTcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE2MjgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MDQxMjE0ZTMxMTZmMTBiYWE1NDU2MzM4NzY4NzUzNDFmYjA3MDc3ZDdjZDY1YWVlMGQwZDgzMjRmOTljNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._OD0-F0vdu0-P_LJjJ3cWdWbd-9143_J4LSotHby30w">
> This is a rough mock-up for our second page AFTER clicking on a specific country on the map e.g. in this case, if we clicked on Canada, we would see this.
> 
> This one needs a bit of work, I am open to suggestions!

Looks Awesome！

**Comment by hbandukw** [comment]
App description:
The "global TB trends" dashboard contains an interactive visualization of tuberculosis data worldwide. The main page displays a color-coded world map tracking TB incidence/mortality from 2000 to 2022 across 217 countries, complemented by toggles for absolute/normalized data and mortality/incidence metrics. A histogram alongside the map is intended to supplement the map by displaying the global trends as a distribution. Clicking on a country brings up a country-specific profile; for instance, selecting Canada reveals detailed metrics, including trends in TB mortality and incidence, case fatality ratio, and TB-HIV co-infection rates, plus a breakdown of risk factors by age and gender, enhancing the user experience with in-depth, localized insights.

**Comment by sandygross** [comment]
I love that, Hina! Thanks. The only thing I would suggest keeping the widgets on the global view and the local view kind of consistent in the sense I would use the widgets used on the "local page" also on the global page. Does that make sense? Otherwise it may be confusing

**Comment by sean-m-mckay** [comment]
> <img alt="main_page_mockup" width="855" src="https://private-user-images.githubusercontent.com/20444993/317361572-a30119dc-77c6-40c0-a0ae-7be38fc4e6f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NTg3NTMsIm5iZiI6MTcxMTU1ODQ1MywicGF0aCI6Ii8yMDQ0NDk5My8zMTczNjE1NzItYTMwMTE5ZGMtNzdjNi00MGMwLWEwYWUtN2JlMzhmYzRlNmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE2NTQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4ODkwMDQ1MmU5MTBkNTg1NmU4Yjc3NmVlZGQxZjZmMGI4MDNhODE3NjQ5Y2FkYjcyY2QwMzMxMmZkNzM0ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g16fPkBq87Q5kXF_nDARrkYZYIkXQfjyQgExzNUCx3A">
> 
> Hi everyone, this is the rough mock-up for our main page showing the global trends of TB.

Absolute/Normalized should be a switch instead of checkbox : ) 

It looks amazing though, great job

**Comment by hbandukw** [comment]
Thanks for the feedback all!! I agree with both @sandygross and @sean-m-mckay. @sandygross for consistency, which type of interactive feature do you want to add?

**Comment by sandygross** [comment]
I think my feedback was little bit confusing. I just wanted to say that we should use the sliders (the type you used for the local page) also on the global page (instead of the checkbox). So I would not change a feature, but only change the type of sliders. Does that make sense?

**Comment by hbandukw** [comment]
This is the updated fig:

<img width="1095" alt="main_page_mockup" src="https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/assets/20444993/ff9394cd-8954-4795-8f7a-3cc743e40c46">

**Comment by zywkloo** [comment]
Will update the annotated later tonight
