### ISSUE TITLE
Add deployment URL in "About" section

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_1_TBtracker#56]
@zywkloo @hbandukw @sean-m-mckay @sandygross I'm reviewing some things regarding the apps that we need for next week. I have noticed that you have not added a deployment URL in the "About" section of your repo. Could you please add it there (see the milestone for instructions)?

**Comment by sean-m-mckay** [comment]
Added now! (the link was previously only in the README [here](https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker?tab=readme-ov-file#access-the-application))
