### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_1_TBtracker#57]
- [x] Outline countries on hover to indicate click. Also indicate click in subtitle/chart title.
- [x] Switch to dbc tabs.
- [x] Remove scroll from both pages
- [x] Maybe remove bar chart? Or indicate country for the bars more cleary? It looks like the x-axis is empty now.
    - [ ] Potentially put in two cars in that place
    - [ ] Or one card and a smaller bar chart

**Comment by zywkloo** [comment]
As we have completed all feedback from Joel. close this issue.
