### ISSUE TITLE
Improvements and Feedback with Joel

### ISSUE THREAD

**Issue by sandygross** [UBC-MDS/DSCI-532_2024_1_TBtracker#58]
Design changes: 
- decrease of width of histogram; generally improve format of plots
- improve begin of tabs (size, color, font)
- change font and color of filter sidebar
- font of the whole page
- add cards: 1, global indicende in absolute/relative numbers (plus comparison to last year)
- indication that you can click/hover
- bootstrap tabs
- remove scrolling on both tabs
- maybe remove histogram (??)))

Modulization of Code:
e.g. separate components

**Comment by sean-m-mckay** [comment]
Closing as we addressed these in separate issues
