### ISSUE TITLE
Change tabs to dbc Bootstrap tabs and change color 

### ISSUE THREAD

**Issue by sandygross** [UBC-MDS/DSCI-532_2024_1_TBtracker#59]
- Increase contrast between highlighted and non-highlighted tab

**Comment by sean-m-mckay** [comment]
I made this change in https://github.com/UBC-MDS/DSCI-532_2024_1_TBtracker/pull/75, but if you want to change the tab colour or any other formatting for the dbc tabs can do that

**Comment by zywkloo** [comment]
It looks nice, I think we can close this issue, thank you!
