### ISSUE TITLE
Proposal: Description of Data

### ISSUE THREAD

**Issue by sean-m-mckay** [UBC-MDS/DSCI-532_2024_1_TBtracker#6]
Writeup of the relevant attributes for the TB dataset

Description 
-------------
You are allowed to select any dataset you want for this project,
as long as you have the license to use it publicly.
Finding a suitable data set can take a lot of time and effort.
You are therefore allowed to select one
that you have worked with in a previous lab/project in MDS
if you wish.

A few datasets that have been popular in previous years:

- https://www.kaggle.com/zynicide/wine-reviews/data
- https://github.com/themarshallproject/city-crime
- https://archive.ics.uci.edu/dataset/45/heart+disease

Good general resources for finding interesting datasets:

- https://github.com/fivethirtyeight/data
- https://github.com/the-pudding/data
- https://www.kaggle.com/datasets
- https://ourworldindata.org/teaching#how-can-i-use-our-world-in-data-to-teach
- https://opendata.vancouver.ca/
- https://archive.ics.uci.edu/

In your proposal,
briefly describe the dataset and the variables that you will visualize:

- Include how many rows and columns there are in the dataset (that you plan to use).
- There should be a clear link to how the dataset and the variables you describe will help you solve your target audience's problem.
- Indicate at least one new variable that you are planning to derive/engineer for your visualizations.
    - If there are no new variables to derive,
      indicate what additional information you would have liked to have in the dataset
      to better be able to answer your research questions (even if it is impossible for you to engineer it).
- If you are planning to visualize a lot of columns,
  provide a high level description of the variable types rather than listing every single column.
    - For example,
      indicate that the dataset contains a variety of categorical variables for demographics
      and provide a brief list rather than describing every single variable.
    - You may also want to consider visualizing a smaller set of variables given the short duration of this project.

To be able to include this information
you might wish to perform a brief exploratory data analysis
for you to grasp what could be interesting variables to look at in your data.
We will not be grading the EDA aspect,
but include your EDA notebooks in the public GitHub repo,
so that you have everything in one place.

Example writeup:

> We will be visualizing a dataset of approximately 300,000 missed patient appointments.
> Each appointment has 15 associated variables
> that describe the following characteristics,
> which we hypothesize could be helpful in determining why patient's miss their appointments:
>
> - Patient demographics (`patient_id`, `gender`, `age`, etc)
> - The health status of the patient (`general_health_status`, `existing_conditions` e.g. "Hypertension", "Physical disability")
> - Information about the appointment itself (`appointment_id`, `appointment_date`)
> - Whether the patient received a reminder about the appointment (`reminder_sent`)
> - Whether the patient showed up (`status`)
>
> Using this data we will also derive new variables,
> such as the time since the patient's last appointment (`days_since_last_appointment`)
> and which weekday the appointment was on (`appointment_weekday`),
> as it would be interesting to explore if these could be linked to the patient missing their appointment.

Another example of [a good description of a dataset is the Kaggle world happiness report](https://www.kaggle.com/unsdsn/world-happiness).

**Comment by hbandukw** [comment]
I have added the data description to m1_proposal.md along with the suggested changes.
