### ISSUE TITLE
Feedback from Kittipong Wongwipasamitkun

### ISSUE THREAD

**Issue by jokittipong** [UBC-MDS/DSCI-532_2024_1_TBtracker#76]
- [x] For the overview picture, if you could display all the graphs for each page (whether global data or country-specific) on one page without the need for scrolling, it would be great to Belinda, your target audience (director of Clinical Operations at the NGO TB Alliance),  for making comparisons.

- [x] Color on global data page doesn't convey the severity of the issue or provide sufficient contrast between countries with low TB rates and those facing serious TB problems. This will help Belinda more on grabbing a good sense of the incidence rate across different countries.

- [x] For the 'relative numbers' filter choice, it's not quite clear how it relates to its own country's population, to a region, to the world population, or only to patient numbers compared within a region or at a global level. Please specify more for greater precision. This will prevent confusion to any users.

- [ ] Year Selection drop down, in my opinion, if you can make it like timeline to select it would look more interesting and also the user can see the visual of the timeline of the data they have. This will give user like Belinda a better sense to keep track on the data by looking on this year timeline. 

- [x] I love how you make it possible to click on the map and show the country information on a country-specific page. If you could add this kind of clickability to the bar chart as well, it would be great. This will provide more convenience to many users.

- [x] The bar chart displaying TB incidence by demographic group is difficult to read and compare, especially regarding the total number of TB cases. You could either place the total number on top of each bar in the chart or find another way to convey the total number of incidences, since the hover data only shows the number of cases for males or females separately. This will help users for comparison the total number.

Anyway, great job everyone!

**Comment by sandygross** [comment]
Thank you Kittitpong! We addressed these issues
