### ISSUE TITLE
Feedback from Shizhe Zhang (Vincent)

### ISSUE THREAD

**Issue by zhang-shizhe** [UBC-MDS/DSCI-532_2024_1_TBtracker#79]
First of all, your dashboard is amazing! I love the interaction and design logic! Here are some tips that I think would be helpful to make this dashborad even better.
- [x] Under the "global data" section, it would be better to set the "Year" filter from a dropdown menu to a time range slider. In this way, users can filter multiple years, and do relative analysis based on a wider time range.
- [x] In the "Global Tuberculosis Trend in xxxx" bar plot, it seems the label of x axis is missing. I know it will be a little crowded to show all the coutry names. Maybe you could try to rotate the label vertical instead.
- [x] #133
- [x] #135
- [x] #132
- [x] #131

**Comment by zywkloo** [comment]
We can call him Vincent

**Comment by zywkloo** [comment]
All tasks done
