### ISSUE TITLE
Feedback from Ian MacCarthy

### ISSUE THREAD

**Issue by ianm99** [UBC-MDS/DSCI-532_2024_1_TBtracker#82]
- [x] This doesn't really matter, but when you have code that the user should run like the bash commands in your readme, I think it's nice to specify in what context the user should run it. For example, "run the following code *in your terminal*". Other than that your set-up instructions were wonderfully thorough.
- [x] For some mysterious reason the map hover tooltip doesn't work for countries that are displayed above the card on your landing page (Japan, Philippines, Indonesia, etc.). Also I'm sure you're aware that Australia is obscured... my recommendation would be moving the information displayed in the card over to your sidebar if possible.
- [x] I beg of you to round the relative incidence and mortality rates to a few significant digits and display them as percents XD.
- [x] Your demographic filters might look more polished if you spell out "Female" instead of "f" for instance, and label the filters as sex and age group.
- [x] I looked at the risk factor pie chart for a while but couldn't decide what it means... Are they proportions of cases that coincide with the given risk factor? If so why should those proportions sum to one? I don't know what the solution is, but maybe reconsider how to title and format that graph. Also I feel like subtitles are not illegal in such cases.
- [x] small thing but if I click on a country on the map, I'm redirected to the relevant country specific page which is great! But for some reason the hover tooltip from the graph persists on this new page.

Overall I love the clear uncluttered layout! You guys have done a really great job with this!

**Comment by sandygross** [comment]
Thank you, Ian, we addressed your comments!
