### ISSUE TITLE
Fix Label Filters on Bar Chart

### ISSUE THREAD

**Issue by sean-m-mckay** [UBC-MDS/DSCI-532_2024_1_TBtracker#93]
In the "TB Incidence by Demographic Group" under "Country-Specific" section, it will be better to indicate what the filter is. (sex and age_group). Also, you might want to change the content inside the first filter from "m/f" to "male/female".

Change text to "Select Gender" and "Select Age Group"

**Comment by hbandukw** [comment]
completed and merged!
