### ISSUE TITLE
Add Note on Relative Proportion

### ISSUE THREAD

**Issue by sean-m-mckay** [UBC-MDS/DSCI-532_2024_1_TBtracker#99]
For the 'relative numbers' filter choice, it's not quite clear how it relates to its own country's population, to a region, to the world population, or only to patient numbers compared within a region or at a global level. Please specify more for greater precision. This will prevent confusion to any users.

**Comment by sandygross** [comment]
Hi, I addressed feedback from Kittipong Wongwipasamitkun
